// frontEnd/src/app/components/pedidos/mis-pedidos/mis-pedidos.component.ts
import { Component, inject } from '@angular/core';
import { PedidosService } from '../../../../services/pedidos.service';
import { CervezaService } from '../../../../services/cerveza.service';
import { IAdminPedido } from '../../../models/adminPedido.models';
import { ICerveza } from '../../../models/cerveza.models';
import { AuthService } from '../../../../services/authService';
import { CommonModule } from '@angular/common';
import { MessageService } from 'primeng/api';
import { CardModule } from 'primeng/card';

@Component({
  selector: 'app-mis-pedidos',
  imports: [CardModule, CommonModule],
  templateUrl: './mis-pedidos.component.html',
  styleUrls: ['./mis-pedidos.component.css']
})

export class MisPedidosComponent {
  misPedidos: IAdminPedido[] = [];
  cervezasPorPedido: { [pedidoId: string]: Array<ICerveza & { cantidad: number }> } = {};


  private _pedidosService = inject(PedidosService);
  private _cervezaService = inject(CervezaService);
  private _authService = inject(AuthService);
  private _messageService = inject(MessageService);

  ngOnInit() {
    const usuario = this._authService.getUser();
    if (!usuario || !usuario._id) {
      this._messageService.add({
        severity: 'error',
        summary: 'Error',
        detail: 'Usuario no autenticado'
      });
      window.location.href = '/login';
      return;
    }

    this._pedidosService.getPedidosByUsuario(usuario._id).subscribe({
      next: (pedidos) => {
        this.misPedidos = pedidos;
        this.cervezasPorPedido = {};
        for (const pedido of pedidos) {
          this.cervezasPorPedido[pedido._id] = [];
          for (const item of pedido.cervezas) {
            this._cervezaService.getCervezaById(item.cerveza).subscribe({
              next: (cerveza) => {
                this.cervezasPorPedido[pedido._id].push({
                  ...cerveza,
                  cantidad: item.cantidad
                });
              }
            });
          }
        }
      },
      error: (err) => {
        this._messageService.add({
          severity: 'error',
          summary: 'Error',
          detail: 'No se pudieron cargar los pedidos'
        });
      }
    });
  }
}


<h2 class="mb-6 text-2xl font-bold text-center">Mis Pedidos</h2>
@if (misPedidos && misPedidos.length > 0) {
  <div class="flex flex-wrap gap-8 justify-center">
    @for(pedido of misPedidos; track $index) {
      <div class="bg-gray-800 rounded-lg shadow-lg p-6 w-full sm:w-[350px] md:w-[400px] lg:w-[450px] mb-4 flex-shrink-0">
        <div class="mb-2 text-gray-300 text-sm">Pedido ID: <span class="font-mono">{{ pedido._id }}</span></div>
        <div class="mb-2"><strong class="text-gray-300">Estado:</strong>
          @if (pedido.estado === 'pendiente') {
            <span class="text-yellow-400"> {{ pedido.estado }}</span>
          }
          @if (pedido.estado === 'aprobado') {
            <span class="text-green-400"> {{ pedido.estado }}</span>
          }
          @if (pedido.estado === 'rechazado') {
            <span class="text-red-400"> {{ pedido.estado }}</span>
          }
        </div>
        <div class="mb-2 text-gray-300"><strong class="text-gray-300">Fecha:</strong> {{ pedido.fecha | date: 'dd/MM/yyyy' }}</div>
        @if (pedido.estado === 'pendiente') {
          <div class="mb-2 text-yellow-400">Tu pedido está pendiente de aprobación.</div>
        } @else if (pedido.estado === 'aprobado') {
          <div class="mb-2 text-green-400">Tu pedido ha sido aprobado.</div>
          <div class="mb-2"><strong>Fecha aprobación:</strong> {{ pedido.fecha_aprobacion | date: 'dd/MM/yyyy' }}</div>
        } @else if (pedido.estado === 'rechazado') {
          <div class="mb-2 text-red-400">Tu pedido ha sido rechazado.</div>
        }
        <div class="mb-2"><strong class="text-gray-300">Cervezas solicitadas:</strong>
          <ul class="ml-4 mt-2 flex flex-col gap-2">
            @for(cerveza of cervezasPorPedido[pedido._id]; track $index) {
              <li class="bg-gray-900 rounded px-3 py-2">
                <div><span class="font-semibold text-gray-300">Nombre: </span> <span class="font-bold text-gray-300">{{ cerveza.nombre }}</span></div>
                <div><span class="font-semibold text-gray-300">Tipo: </span> <span class="font-bold text-gray-300">{{ cerveza.tipo }}</span></div>
                <div><span class="font-semibold text-gray-300">Cantidad: </span> <span class="font-bold text-gray-300">{{ cerveza.cantidad }}</span></div>
              </li>
            }
          </ul>
        </div>
      </div>
    }
  </div>
} @else {
  <p class="text-center text-gray-400 mt-8">No tenés pedidos realizados.</p>
}

// frontReact/src/components/pedidos/MisPedidos.tsx
import { useEffect, useState } from 'react';
import { useAuth } from '../../context/AuthContext';
import { useToast } from '../../context/ToastContext';
import * as pedidosService from '../../services/pedidosService';
import * as cervezaService from '../../services/cervezaService';
import type { IAdminPedido } from '../../models/adminPedido.models';
import type { ICerveza } from '../../models/cerveza.models';
import { formatFecha } from '../../utils/date';

/**
 * Equivalente a pedidos/mis-pedidos.component (Angular). Lista los pedidos del cliente.
 * Replica el patrón N+1 (un getCervezaById por ítem) y el bug window.location.href.
 */
export default function MisPedidos() {
  const { user } = useAuth();
  const toast = useToast();

  const [misPedidos, setMisPedidos] = useState<IAdminPedido[]>([]);
  const [cervezasPorPedido, setCervezasPorPedido] = useState<
    Record<string, Array<ICerveza & { cantidad: number }>>
  >({});

  useEffect(() => {
    if (!user || !user._id) {
      toast.show({ severity: 'error', summary: 'Error', detail: 'Usuario no autenticado' });
      window.location.href = '/login';
      return;
    }

    pedidosService
      .getPedidosByUsuario(user._id)
      .then((pedidos) => {
        setMisPedidos(pedidos);
        setCervezasPorPedido({});
        for (const pedido of pedidos) {
          setCervezasPorPedido((prev) => ({ ...prev, [pedido._id]: prev[pedido._id] ?? [] }));
          for (const item of pedido.cervezas) {
            cervezaService.getCervezaById(item.cerveza).then((cerveza) => {
              setCervezasPorPedido((prev) => ({
                ...prev,
                [pedido._id]: [...(prev[pedido._id] ?? []), { ...cerveza, cantidad: item.cantidad }],
              }));
            });
          }
        }
      })
      .catch(() => {
        toast.show({ severity: 'error', summary: 'Error', detail: 'No se pudieron cargar los pedidos' });
      });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <>
      <h2 className="mb-6 text-2xl font-bold text-center">Mis Pedidos</h2>
      {misPedidos && misPedidos.length > 0 ? (
        <div className="flex flex-wrap gap-8 justify-center">
          {misPedidos.map((pedido, i) => (
            <div
              key={pedido._id ?? i}
              className="bg-gray-800 rounded-lg shadow-lg p-6 w-full sm:w-[350px] md:w-[400px] lg:w-[450px] mb-4 flex-shrink-0"
            >
              <div className="mb-2 text-gray-300 text-sm">
                Pedido ID: <span className="font-mono">{pedido._id}</span>
              </div>
              <div className="mb-2">
                <strong className="text-gray-300">Estado:</strong>
                {pedido.estado === 'pendiente' && <span className="text-yellow-400"> {pedido.estado}</span>}
                {pedido.estado === 'aprobado' && <span className="text-green-400"> {pedido.estado}</span>}
                {pedido.estado === 'rechazado' && <span className="text-red-400"> {pedido.estado}</span>}
              </div>
              <div className="mb-2 text-gray-300">
                <strong className="text-gray-300">Fecha:</strong> {formatFecha(pedido.fecha)}
              </div>
              {pedido.estado === 'pendiente' ? (
                <div className="mb-2 text-yellow-400">Tu pedido está pendiente de aprobación.</div>
              ) : pedido.estado === 'aprobado' ? (
                <>
                  <div className="mb-2 text-green-400">Tu pedido ha sido aprobado.</div>
                  <div className="mb-2">
                    <strong>Fecha aprobación:</strong> {formatFecha(pedido.fecha_aprobacion)}
                  </div>
                </>
              ) : pedido.estado === 'rechazado' ? (
                <div className="mb-2 text-red-400">Tu pedido ha sido rechazado.</div>
              ) : null}
              <div className="mb-2">
                <strong className="text-gray-300">Cervezas solicitadas:</strong>
                <ul className="ml-4 mt-2 flex flex-col gap-2">
                  {(cervezasPorPedido[pedido._id] ?? []).map((cerveza, j) => (
                    <li key={j} className="bg-gray-900 rounded px-3 py-2">
                      <div>
                        <span className="font-semibold text-gray-300">Nombre: </span>
                        <span className="font-bold text-gray-300">{cerveza.nombre}</span>
                      </div>
                      <div>
                        <span className="font-semibold text-gray-300">Tipo: </span>
                        <span className="font-bold text-gray-300">{cerveza.tipo}</span>
                      </div>
                      <div>
                        <span className="font-semibold text-gray-300">Cantidad: </span>
                        <span className="font-bold text-gray-300">{cerveza.cantidad}</span>
                      </div>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          ))}
        </div>
      ) : (
        <p className="text-center text-gray-400 mt-8">No tenés pedidos realizados.</p>
      )}
    </>
  );
}
