// frontReact/src/components/Register.tsx
import { useState } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { InputText } from 'primereact/inputtext';
import { Password } from 'primereact/password';
import { Button } from 'primereact/button';
import { useAuth } from '../context/AuthContext';

/**
 * Equivalente a register.component (Angular). Se usa en:
 *  - /register            (registro de cliente, vía GuestRoute)
 *  - /admin/crear-empleado (alta de empleado, vía ProtectedRoute roles=['admin'])
 * El caso se distingue por la URL, igual que el original (router.url.startsWith).
 *
 * Nota: el original tenía `loading` y `successMessage` que el template no renderiza
 * (código muerto); se omiten. Comportamiento observable idéntico.
 */
const EMAIL_PATTERN = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

export default function Register() {
  const { register } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();
  const isAdminCreatingEmployee = location.pathname.startsWith('/admin/crear-empleado');

  const [nombre, setNombre] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [nombreTouched, setNombreTouched] = useState(false);
  const [emailTouched, setEmailTouched] = useState(false);
  const [passwordTouched, setPasswordTouched] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');

  const nombreInvalid = nombre === '';
  const emailRequiredError = email === '';
  const emailFormatError = email !== '' && !EMAIL_PATTERN.test(email);
  const emailInvalid = emailRequiredError || emailFormatError;
  const passwordInvalid = password === '';
  const formInvalid = nombreInvalid || emailInvalid || passwordInvalid;

  const onRegister = async (e: React.FormEvent) => {
    e.preventDefault();
    if (formInvalid) return;

    setErrorMessage('');
    const payload = {
      nombre,
      email,
      password,
      ...(isAdminCreatingEmployee ? { rol: 'empleado' } : {}),
    };

    try {
      await register(payload);
      setNombre('');
      setEmail('');
      setPassword('');
      setNombreTouched(false);
      setEmailTouched(false);
      setPasswordTouched(false);
      if (!isAdminCreatingEmployee) {
        navigate('/login?registrado=true');
      } else {
        navigate('/admin?registrado=true');
      }
    } catch (err: any) {
      setErrorMessage(err?.message || 'Error al registrar usuario');
    }
  };

  return (
    <div className="flex justify-center min-h-screen items-start">
      <div className="bg-gray-100 p-8 rounded-md shadow-md w-full max-w-md">
        <h2 className="text-xl font-bold mb-6 text-center">
          {isAdminCreatingEmployee ? 'Registrar Empleado' : 'Registro de Usuario'}
        </h2>

        {isAdminCreatingEmployee && (
          <p className="text-sm text-gray-600 text-center mb-4">
            Completá los datos para dar de alta un nuevo empleado.
          </p>
        )}

        <form onSubmit={onRegister}>
          <div className="mb-4">
            <label className="block mb-2 font-medium">Nombre</label>
            <InputText
              type="text"
              className="w-full"
              value={nombre}
              onChange={(e) => setNombre(e.target.value)}
              onBlur={() => setNombreTouched(true)}
            />
            {nombreInvalid && nombreTouched && (
              <small className="text-red-500 mt-2">El nombre es obligatorio.</small>
            )}
          </div>

          <div className="mb-4">
            <label className="block mb-2 font-medium">Email</label>
            <InputText
              type="email"
              className="w-full"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              onBlur={() => setEmailTouched(true)}
            />
            {emailInvalid && emailTouched && (
              <small className="text-red-500 mt-2">
                {emailRequiredError ? 'El email es obligatorio.' : 'El email no es válido.'}
              </small>
            )}
          </div>

          <div className="mb-4">
            <label className="block mb-2 font-medium">Contraseña</label>
            <Password
              className="w-full"
              inputClassName="w-full"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              onBlur={() => setPasswordTouched(true)}
            />
            {passwordInvalid && passwordTouched && (
              <small className="text-red-500 mt-2">La contraseña es obligatoria.</small>
            )}
          </div>

          <div className="mb-2">{errorMessage && <p className="text-red-500 mt-2">{errorMessage}</p>}</div>

          <Button
            type="submit"
            label={isAdminCreatingEmployee ? 'Registrar Empleado' : 'Registrarse'}
            className="w-full"
          />
        </form>

        {!isAdminCreatingEmployee && (
          <div className="mt-4 text-center">
            <p className="text-sm text-gray-600">
              ¿Ya tenés una cuenta?{' '}
              <a href="/login" className="text-blue-600 hover:underline font-medium">
                Ingresa acá
              </a>
            </p>
          </div>
        )}
      </div>
    </div>
  );
}

// frontEnd/src/app/components/register/register.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common'; 
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule  } from '@angular/forms';
import { ButtonModule } from 'primeng/button';
import { InputTextModule } from 'primeng/inputtext';
import { PasswordModule } from 'primeng/password';
import { AuthService } from '../../../services/authService';
import { ActivatedRoute, Router } from '@angular/router';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  imports: [ButtonModule, InputTextModule, PasswordModule, ReactiveFormsModule, CommonModule],
  standalone: true,
})

export class RegisterComponent {
  registerForm: FormGroup;
  loading = false;
  errorMessage :string = '';
  successMessage :string = '';
  isAdminCreatingEmployee:boolean = false;

  constructor(private fb: FormBuilder, private authService: AuthService, private router:Router, private route: ActivatedRoute) {
    this.registerForm = this.fb.group({
      nombre: ['', Validators.required],
      email: ['', [Validators.required, Validators.email]],
      password: ['', Validators.required],
    });

    this.isAdminCreatingEmployee = this.router.url.startsWith('/admin/crear-empleado');
  }

  async onRegister() {
      if (this.registerForm.invalid) return;

      this.loading = true;
      this.errorMessage = '';
      this.successMessage = '';

      const payload = {
        ...this.registerForm.value,
        ...(this.isAdminCreatingEmployee ? { rol: 'empleado' } : {}),
      };
      console.log(payload)
      try {
        const res = await this.authService.register(payload);
        console.log(res)
        this.successMessage = 'Usuario registrado correctamente';
        this.registerForm.reset();
        if(!this.isAdminCreatingEmployee){
          this.router.navigate(['/login'], { queryParams: { registrado: true } });
        }else{
          this.router.navigate(['/admin'], { queryParams: { registrado: true } });
        }
        
      } catch (err: any) {
        this.errorMessage = err.message || 'Error al registrar usuario';
      } finally {
        this.loading = false;
      }
  }

  get nombre() {
    return this.registerForm.get('nombre')!;
  }

  get email() {
    return this.registerForm.get('email')!;
  }

  get password() {
    return this.registerForm.get('password')!;
  }
}

<div class="flex justify-center  min-h-screen items-start">
  <div class="bg-gray-100 p-8 rounded-md shadow-md w-full max-w-md">
    <h2 class="text-xl font-bold mb-6 text-center">
      {{ isAdminCreatingEmployee ? 'Registrar Empleado' : 'Registro de Usuario' }}
    </h2>

    <p *ngIf="isAdminCreatingEmployee" class="text-sm text-gray-600 text-center mb-4">
      Completá los datos para dar de alta un nuevo empleado.
    </p>
    
    <form [formGroup]="registerForm" (ngSubmit)="onRegister()" >
      <div class="mb-4">
        <label class="block mb-2 font-medium">Nombre</label>
        <input type="text" pInputText class="w-full" formControlName="nombre" />
        <small class="text-red-500 mt-2" *ngIf="nombre.invalid && nombre.touched">
            El nombre es obligatorio.
        </small>
      </div>

      <div class="mb-4">
        <label class="block mb-2 font-medium">Email</label>
        <input type="email" pInputText class="w-full" formControlName="email" />
        <small class="text-red-500 mt-2" *ngIf="email.invalid && email.touched">
            <ng-container *ngIf="email.errors?.['required']">El email es obligatorio.</ng-container>
            <ng-container *ngIf="email.errors?.['email']">El email no es válido.</ng-container>
        </small>
      </div>

      <div class="mb-4">
        <label class="block mb-2 font-medium">Contraseña</label>
        <input type="password" pPassword class="w-full" formControlName="password" />
        <small class="text-red-500 mt-2" *ngIf="password.invalid && password.touched">
            La contraseña es obligatoria.
        </small>
      </div>

      <div class="mb-2">
        <p *ngIf="errorMessage" class="text-red-500 mt-2">{{ errorMessage }}</p>
      </div>  

      <button pButton type="submit" 
              [label]="isAdminCreatingEmployee ? 'Registrar Empleado' : 'Registrarse'" 
              class="w-full">
      </button>
    </form>

    <div class="mt-4 text-center" *ngIf="!isAdminCreatingEmployee">
        <p class="text-sm text-gray-600">
            ¿Ya tenés una cuenta?
            <a href="/login" class="text-blue-600 hover:underline font-medium">Ingresa acá</a>
        </p>
    </div>
  </div>
</div>
