// frontReact/src/components/stock/CervezaForm.tsx
import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { InputText } from 'primereact/inputtext';
import { InputNumber } from 'primereact/inputnumber';
import { Checkbox } from 'primereact/checkbox';
import { Button } from 'primereact/button';
import * as cervezaService from '../../services/cervezaService';
import type { ICerveza } from '../../models/cerveza.models';

/**
 * Equivalente a stock/cerveza-form.component (Angular).
 * Sirve para crear (/stock/crearCerveza) y editar (/stock/editarCerveza/:id).
 * Al guardar navega a /stock con ?creado=true o ?editado=true.
 */
export default function CervezaForm() {
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();

  const [cerveza, setCerveza] = useState<ICerveza>({
    nombre: '',
    tipo: '',
    stock_actual: 0,
    stock_minimo: 0,
    activo: true,
  });
  const [error, setError] = useState('');
  const [erroresForm, setErroresForm] = useState<Record<string, string>>({});

  useEffect(() => {
    if (id) {
      cervezaService
        .getCervezaById(id)
        .then((data) => setCerveza(data))
        .catch(() => {
          setError('No se pudo cargar la cerveza.');
          console.error('Error cargando cerveza');
        });
    }
  }, [id]);

  const validar = (): boolean => {
    const errs: Record<string, string> = {};
    const { nombre, tipo, stock_actual, stock_minimo } = cerveza;

    if (!nombre.trim()) {
      errs['nombre'] = 'El nombre es obligatorio.';
    }
    if (!tipo.trim()) {
      errs['tipo'] = 'El tipo es obligatorio.';
    }
    if (stock_actual < 0) {
      errs['stock_actual'] = 'El stock actual no puede ser negativo.';
    }
    if (stock_minimo < 0) {
      errs['stock_minimo'] = 'El stock mínimo no puede ser negativo.';
    }

    setErroresForm(errs);
    setError('');
    return Object.keys(errs).length === 0;
  };

  const guardar = () => {
    if (!validar()) return;

    if (id) {
      cervezaService
        .updateCerveza(id, cerveza)
        .then(() => navigate('/stock?editado=true'))
        .catch(() => setError('Error actualizando la cerveza.'));
    } else {
      cervezaService
        .createCerveza(cerveza)
        .then(() => navigate('/stock?creado=true'))
        .catch(() => setError('Error creando la cerveza.'));
    }
  };

  const cancelar = () => navigate('/stock');

  return (
    <div className="p-4 max-w-lg mx-auto">
      <h2 className="text-xl font-semibold mb-4">{id ? 'Editar Cerveza' : 'Nueva Cerveza'}</h2>

      <div className="mb-3">
        <label htmlFor="nombre" className="block mb-1 font-medium">
          Nombre
        </label>
        <InputText
          id="nombre"
          type="text"
          value={cerveza.nombre}
          onChange={(e) => setCerveza({ ...cerveza, nombre: e.target.value })}
        />
        {erroresForm['nombre'] && <div className="text-red-600 text-sm">{erroresForm['nombre']}</div>}
      </div>

      <div className="mb-3">
        <label htmlFor="tipo" className="block mb-1 font-medium">
          Tipo
        </label>
        <InputText
          id="tipo"
          type="text"
          value={cerveza.tipo}
          onChange={(e) => setCerveza({ ...cerveza, tipo: e.target.value })}
        />
        {erroresForm['tipo'] && <div className="text-red-600 text-sm">{erroresForm['tipo']}</div>}
      </div>

      <div className="mb-3">
        <label htmlFor="stock_actual" className="block mb-1 font-medium">
          Stock Actual
        </label>
        <InputNumber
          inputId="stock_actual"
          value={cerveza.stock_actual}
          min={0}
          onValueChange={(e) => setCerveza({ ...cerveza, stock_actual: e.value ?? 0 })}
        />
        {erroresForm['stock_actual'] && (
          <div className="text-red-600 text-sm">{erroresForm['stock_actual']}</div>
        )}
      </div>

      <div className="mb-3">
        <label htmlFor="stock_minimo" className="block mb-1 font-medium">
          Stock Mínimo
        </label>
        <InputNumber
          inputId="stock_minimo"
          value={cerveza.stock_minimo}
          min={0}
          onValueChange={(e) => setCerveza({ ...cerveza, stock_minimo: e.value ?? 0 })}
        />
        {erroresForm['stock_minimo'] && (
          <div className="text-red-600 text-sm">{erroresForm['stock_minimo']}</div>
        )}
      </div>

      <div className="mb-3 flex items-center">
        <Checkbox
          inputId="activo"
          checked={cerveza.activo}
          onChange={(e) => setCerveza({ ...cerveza, activo: e.checked ?? false })}
        />
        <label htmlFor="activo" className="ml-2">
          Activo
        </label>
      </div>

      {error && (
        <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-2 rounded mb-4">
          {error}
        </div>
      )}

      <div className="flex justify-between mt-6">
        <Button label="Guardar" className="p-button-success" onClick={guardar} />
        <Button label="Cancelar" className="p-button-secondary" onClick={cancelar} />
      </div>
    </div>
  );
}

// frontEnd/src/app/components/stock/cerveza-form/cerveza-form.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ButtonModule } from 'primeng/button';
import { InputTextModule } from 'primeng/inputtext';
import { InputNumberModule } from 'primeng/inputnumber';
import { CheckboxModule } from 'primeng/checkbox';
import { CervezaService } from '../../../../services/cerveza.service';

@Component({
  selector: 'app-cerveza-form',
  templateUrl: './cerveza-form.component.html',
  styleUrls: ['./cerveza-form.component.css'],
  imports: [
    CommonModule,
    FormsModule,
    ButtonModule,
    InputTextModule,
    InputNumberModule,
    CheckboxModule,
  ]
})
export class CervezaFormComponent implements OnInit {

  id?: string;

  cerveza = {
    nombre: '',
    tipo: '',
    stock_actual: 0,
    stock_minimo: 0,
    activo: true
  };

  error: string = '';
  errores_form: { [campo: string]: string } = {};

  constructor(
    private route: ActivatedRoute, 
    private router: Router, 
    private cervezaService: CervezaService,
    
  ) {}

  ngOnInit(): void {
    this.id = this.route.snapshot.paramMap.get('id') || undefined;

    if (this.id) {
      this.cervezaService.getCervezaById(this.id).subscribe({
        next: (data) => this.cerveza = data,
        error: () => {
          this.error = 'No se pudo cargar la cerveza.';
          console.error('Error cargando cerveza');
        }
      });
    }
  }

  validar(): boolean {
    this.errores_form = {};
    this.error = ""

    const { nombre, tipo, stock_actual, stock_minimo } = this.cerveza;

    if (!nombre.trim()) {
      this.errores_form['nombre'] = 'El nombre es obligatorio.';
    }

    if (!tipo.trim()) {
      this.errores_form['tipo'] = 'El tipo es obligatorio.';
    }

    if (stock_actual < 0) {
      this.errores_form['stock_actual'] = 'El stock actual no puede ser negativo.';
    }

    if (stock_minimo < 0) {
      this.errores_form['stock_minimo'] = 'El stock mínimo no puede ser negativo.';
    }

    this.error = '';
    
    return Object.keys(this.errores_form).length === 0;
  }

  guardar() {
    
    if (!this.validar()) return;

    if (this.id) {
      this.cervezaService.updateCerveza(this.id, this.cerveza).subscribe({
        next: () => this.router.navigate(['/stock'], { queryParams: { editado: true } }),
        error: (err) => {
          this.error = 'Error actualizando la cerveza.';
        }
      });
    } else {
      this.cervezaService.createCerveza(this.cerveza).subscribe({
        next: () => this.router.navigate(['/stock'], { queryParams: { creado: true } }),
        error: (err) => {
          this.error = 'Error creando la cerveza.';
        }
      });
    }
  }

  cancelar() {
    this.router.navigate(['/stock']);
  }
}


<div class="p-4 max-w-lg mx-auto">
  <h2 class="text-xl font-semibold mb-4">
    {{ id ? 'Editar Cerveza' : 'Nueva Cerveza' }}
  </h2>

  <div class="mb-3">
    <label for="nombre" class="block mb-1 font-medium">Nombre</label>
    <input id="nombre" type="text" [(ngModel)]="cerveza.nombre" pInputText />
    <div *ngIf="errores_form['nombre']" class="text-red-600 text-sm">{{ errores_form['nombre'] }}</div>
  </div>

  <div class="mb-3">
    <label for="tipo" class="block mb-1 font-medium">Tipo</label>
    <input id="tipo" type="text" [(ngModel)]="cerveza.tipo" pInputText />
    <div *ngIf="errores_form['tipo']" class="text-red-600 text-sm">{{ errores_form['tipo'] }}</div>
  </div>

  <div class="mb-3">
    <label for="stock_actual" class="block mb-1 font-medium">Stock Actual</label>
    <p-inputNumber [(ngModel)]="cerveza.stock_actual" [min]="0"></p-inputNumber>
    <div *ngIf="errores_form['stock_actual']" class="text-red-600 text-sm">{{ errores_form['stock_actual'] }}</div>
  </div>

  <div class="mb-3">
    <label for="stock_minimo" class="block mb-1 font-medium">Stock Mínimo</label>
    <p-inputNumber [(ngModel)]="cerveza.stock_minimo" [min]="0"></p-inputNumber>
    <div *ngIf="errores_form['stock_minimo']" class="text-red-600 text-sm">{{ errores_form['stock_minimo'] }}</div>
  </div>

  <div class="mb-3 flex items-center">
    <p-checkbox [(ngModel)]="cerveza.activo" binary="true" inputId="activo"></p-checkbox>
    <label for="activo" class="ml-2">Activo</label>
  </div>

  <div *ngIf="error" class="bg-red-100 border border-red-400 text-red-700 px-4 py-2 rounded mb-4">
    {{ error }}
  </div>

  <div class="flex justify-between mt-6">
    <button pButton label="Guardar" class="p-button-success" (click)="guardar()"></button>
    <button pButton label="Cancelar" class="p-button-secondary" (click)="cancelar()"></button>
  </div>

  
</div>
