// frontEnd/src/app/components/admin-dashboard/admin-dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ListaUsuariosComponent } from '../../../app/components/lista-usuarios/lista-usuarios.component';

@Component({
  selector: 'app-admin-dashboard',
  standalone: true,
  imports: [CommonModule, ListaUsuariosComponent],
  templateUrl: './admin-dashboard.component.html',
  styleUrls: ['./admin-dashboard.component.css']
})

export class AdminDashboardComponent implements OnInit {
  

  ngOnInit(): void {
    
  }
}
<div style="padding: 20px;">
  <h1>Panel de Administración</h1>
  <p>Bienvenido al dashboard de administración.</p>

  <app-lista-usuarios></app-lista-usuarios>

  </div>

// frontReact/src/components/AdminDashboard.tsx
import ListaUsuarios from './ListaUsuarios';

/**
 * Equivalente a admin-dashboard.component (Angular). Contenedor del listado de usuarios.
 */
export default function AdminDashboard() {
  return (
    <div style={{ padding: '20px' }}>
      <h1>Panel de Administración</h1>
      <p>Bienvenido al dashboard de administración.</p>

      <ListaUsuarios />
    </div>
  );
}
